# Generated by Django 3.2.4 on 2021-06-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=255, null=True)),
                ('foto', models.CharField(default=None, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, default=None, null=True)),
                ('link_scholar', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
