# Generated by Django 3.2.4 on 2021-06-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reksis_dosbing', '0002_interests_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='alumni',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='fname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='home_base',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='lname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='nip',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pendidikan',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
